### ISSUE TITLE
Circuit Design/Printing

### ISSUE THREAD

**Issue by marycarmen1999** [Kaixinwang99/The-Gaming-Gauntlet#6]
- [x] Schematic
- [x] PCB design
- [ ] PCB printing

**Comment by marycarmen1999** [comment]
PCB format changed to a 2 part PCB. 

Hand part contains: Flex Sensors, Gyro and ADC. (Done) - Needs Printing

Arm part contains: RaspPi, Ethernet cable, I2C bus (maybe)- To Do

**Comment by Kaixinwang99** [comment]
the design is done, wait to send to china print and deliver to UK it should takes 5-9 days
